version: 2
jobs:
  debug_build_and_test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Apply permissions
          command: chmod +x ./gradlew
      - run:
          name: Approve license for build tools
          command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Clean Build
          command: ./gradlew clean
      - run:
          name: Run Build
          command: ./gradlew assembleDebug
      - run:
          name: Run Lint
          command: ./gradlew lintDebug

      - store_artifacts:
          path: core/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2
  debug_build_and_test:
    jobs:
      - debug_build_and_test:
          filters:
            branches:
              only:
                - develop
                - /^feature.*/